# Generated by Django 4.1.7 on 2023-03-16 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_game_price"),
        ("shop", "0002_alter_purchasehistory_who_buy_alter_user_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="who_buy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Вы",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="BuyGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "what_buy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_buy",
                        to="catalog.game",
                    ),
                ),
                (
                    "who_buy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_buy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
