# Generated by Django 4.1.7 on 2023-03-16 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_game_price"),
        ("shop", "0005_alter_purchasehistory_purchase_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="purchase_price",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.game",
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="who_buy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Вы",
            ),
        ),
    ]
