# Generated by Django 4.1.7 on 2023-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_purchasehistory_purchase_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasehistory",
            name="who_buy",
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
