# Generated by Django 4.1.7 on 2023-03-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_purchasehistory_who_buy_purchasehistory_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
