# Generated by Django 4.1.7 on 2023-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_ganregame_games_game_games"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
